### ISSUE TITLE
Sidekiq check doesn't work

### ISSUE THREAD

**Issue by alexandrz** [sportngin/okcomputer#73] opened 2015-10-22 08:17 UTC
I am getting an exception `uninitialized constant Sidekiq::Queue`

**Comment by jphenow** [comment] 2015-10-22 14:02
Have you tried `require "sidekiq/api"` before okcomputer initializes?

**Comment by jphenow** [comment] 2015-10-22 14:11
We should either document this or make it more automatic in the gem. The problem is that the api file is only required here: 

```
examples/sinkiq.rb
10:require 'sidekiq/api'

lib/sidekiq/middleware/server/retry_jobs.rb
2:require 'sidekiq/api'

lib/sidekiq/scheduled.rb
4:require 'sidekiq/api'

lib/sidekiq/web.rb
6:require 'sidekiq/api'
```

from within the sidekiq gem. So it looks like you'd have to be: using the web interface, a scheduled job or retry job to have accidentally received `Resque::Queue` constant.

**Comment by anfleene** [comment] 2015-10-22 14:14
We could probably add a require to the top of that check and stub it out in a test.

**Comment by jphenow** [comment] 2015-10-22 14:15
Yep totally - was just making the comment so @alexandrz could try to fix it in his local first, but yea we should add the require inside the gem.

**Comment by anfleene** [comment] 2015-10-22 14:15
Getting the gem require to work without adding it as a gem dep could be tricky though.

**Comment by jphenow** [comment] 2015-10-22 14:16
```ruby
if defined?(Sidekiq)
  require 'sidekiq/api'
end
```

**Comment by anfleene** [comment] 2015-10-22 14:18
Yeah that should work good call.

**Comment by anfleene** [comment] 2016-02-29 15:05
I'm going to go ahead and close this out. We should probably talk more about auto requiring things but I'll add that to the 2.0 discussions.

**Closed by anfleene** 2016-02-29 15:05 UTC
